### ISSUE TITLE
npm install failure due to postInstall script

### ISSUE THREAD

**Issue by ycao56** [ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib#13]
For those modules with nlc capabilities, `postInsall: initDb src/nlc/NLC.json` has been added in order to initialize the db automatically after install. If user install it twice, it will fail with below errors

> initDb src/nlc/NLC.json

{ [conflict: Document update conflict]
  status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true }

**Comment by ycao56** [comment]
https://github.com/ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib/blob/master/src/lib/initDb.js#L114 exits the process and fails the install

**Comment by ycao56** [comment]
@normanb I previously talked to @jlpadilla about this. Can you take a look? Can we throw a warning instead of failing the install when db already exists?

**Comment by normanb** [comment]
yes, definitely. I can change that.
