### ISSUE TITLE
Extract a NLC util or helper from the NLCManager

### ISSUE THREAD

**Issue by kevan-ibm** [ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib#51]
The NLCManager has a lot of great function but it is too closely related to a specific training use case.  This issue aims to extract useful function into a more general util.  The NLCManager would maintain the same API, but utilize this new util to perform actions.

@jlpadilla

**Comment by jlpadilla** [comment]
After talking with @kholdaway we decided that this enhancement is not needed at this time.
