### ISSUE TITLE
add cli spinner to indicate when classifier is in training

### ISSUE THREAD

**Issue by aeweidne** [ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib#8]
Per @nbarker suggestion, we should try to use cli-spinner to indicate when the Watson NLC classifier is training.

https://www.npmjs.com/package/cli-spinner

another option:

https://www.npmjs.com/package/elegant-spinner

**Comment by chambrid** [comment]
Not clear how this would be used as the training is done asynchronously. We are adding a status query: https://github.com/ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib/issues/22

FYI @jlpadilla

**Comment by clanzen** [comment]
Agreed.  If a visual spinner sat there for 10 - 15 minutes, it would make the user feel like they need to wait before doing anything else.  That isn't the case.  I haven't looked into #22 but the best we can do is printing out a periodic emit on status (every 5 minutes maybe) and/or allowing a command to directly poll the status.

**Comment by jlpadilla** [comment]
Agreed that this isn't needed, added more logging with #28. When enabled it will print to the console every 60 seconds when a classifier is being trained.
